# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5e65af09048f65110ce09549c4fb547aa6230e51da87a672518e0fcf60ed65f7de85d01d90185fd1b5fe63a71f5f84a82a08916321fc3cad5844bec33213059

test:
  secret_key_base: 5a7625e0f6bbd1bf5d7277d8a6bfdd5c9a961038f64f6c6bbf61b22988286896ff921e9e9239e6eb03ca18bc679db25e3055576c95bccf60d01c2d2ab4375955

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
